add: more stuff to centos7-init script

diff --git a/bin/centos7-init b/bin/centos7-init
--- a/bin/centos7-init
+++ b/bin/centos7-init
@@ -2,28 +2,50 @@
 
 # Prepare a CentOS7 machine as server, from minimal installation
 
-# Unofficial Bash Strict Mode (http://redsymbol.net/articles/unofficial-bash-strict-mode/)
-set -euo pipefail
+# Bash strict mode (https://github.com/alphabetum/bash-boilerplate)
+set -eEuo pipefail
+trap 'echo "Aborting due to errexit on line $LINENO. Exit code: $?" >&2' ERR
+IFS=$'\n\t'
+
+# Lock down /tmp, /var/tmp, and /dev/shm
+awk '!/^#/ && ($2 == "/tmp") { if(!match($4, /nodev/)) $4=$4",nodev" } 1' \
+	/etc/fstab > /tmp/new_fstab
+mv /tmp/new_fstab /etc/fstab
+awk '!/^#/ && ($2 == "/tmp") { if(!match($4, /noexec/)) $4=$4",noexec" } 1' \
+	/etc/fstab > /tmp/new_fstab
+mv /tmp/new_fstab /etc/fstab
+awk '!/^#/ && ($2 == "/tmp") { if(!match($4, /nosuid/)) $4=$4",nosuid" } 1' \
+	/etc/fstab > /tmp/new_fstab
+mv /tmp/new_fstab /etc/fstab
+echo '/tmp   /var/tmp  none   bind,rw,nodev,noexec,nosuid   0 0' >> /etc/fstab
+echo 'tmpfs  /dev/shm  tmpfs  defaults,nodev,noexec,nosuid  0 0' >> /etc/fstab
 
 # Install EPEL repository
-sudo yum -y install epel-release
+yum -y install epel-release
 
 # Install ripgrep COPR repository
-sudo yum-config-manager --add-repo=https://copr.fedorainfracloud.org/coprs/carlwgeorge/ripgrep/repo/epel-7/carlwgeorge-ripgrep-epel-7.repo
+yum-config-manager --add-repo=https://copr.fedorainfracloud.org/coprs/carlwgeorge/ripgrep/repo/epel-7/carlwgeorge-ripgrep-epel-7.repo
 
 # Remove unwanted items
-sudo yum -y erase chrony
+yum -y erase aic94xx-firmware alsa* chrony firewalld iwl*firmware postfix 
 
 # Update everything
-sudo yum -y update
+yum -y update
 
 # Install necessary items
-sudo yum -y install aria2 deltarpm git ripgrep vim-enhanced tmux yum-{cron,utils}
+yum -y install aide aria2 bash-completion bind-utils deltarpm fail2ban git \
+	htop lsof ntp psmisc ripgrep vim-enhanced tmux yum-{cron,utils}
 
-# Filebeat (Elastic Stack)
+# Install VM tools as needed
+if dmesg | grep -q "Hypervisor detected: KVM"; then
+	yum -y install qemu-guest-agent
+	systemctl enable qemu-guest-agent
+fi
+
+# Function to install Filebeat (Elastic Stack)
 install_filebeat() {
-	sudo rpm --import https://packages.elastic.co/GPG-KEY-elasticsearch
-	cat >elastic.6.repo <<EOL
+	rpm --import https://packages.elastic.co/GPG-KEY-elasticsearch
+	cat > /etc/yum.repos.d/elastic.6.repo <<EOL
 [elastic-6.x]
 name=Elastic repository for 6.x packages
 baseurl=https://artifacts.elastic.co/packages/6.x/yum
@@ -33,18 +55,19 @@ enabled=1
 autorefresh=1
 type=rpm-md
 EOL
-	sudo mv elastic.6.repo /etc/yum.repos.d/
-	sudo yum -y install filebeat
+	yum -y install filebeat
 	while true; do
 		read -r -p "Start Filebeat at next boot? [y/N]: " -n 1 ins
 		printf '\n'
 		case $ins in
-			[Yy]* ) sudo systemctl enable filebeat; break;;
+			[Yy]* ) systemctl enable filebeat; break;;
 			[Nn]* ) break;;
 			"" ) break;;
 		esac
 	done
 }
+
+# Install Filebeat as desired
 while true; do
 	read -r -p "Install Filebeat for Elastic Stack? [y/N]: " -n 1 ins
 	printf '\n'
@@ -64,4 +87,4 @@ cd -- dotfiles || exit
 cd "$dir" || exit
 
 # Basic firewall
-sudo ~/dotfiles/bin/fw-cmd-init
+~/dotfiles/bin/iptables-init
