chg: more CS483 work

diff --git a/bin/receive b/bin/receive
--- a/bin/receive
+++ b/bin/receive
@@ -1,14 +1,21 @@
 #!/usr/bin/env bash
 
 # Bash strict mode (https://github.com/alphabetum/bash-boilerplate)
-set -eEuo pipefail
-trap 'echo "Aborting (errexit line $LINENO). Exit code: $?" >&2' ERR
+# set -eEuo pipefail
+# trap 'echo "Aborting (errexit line $LINENO). Exit code: $?" >&2' ERR
 
-for i in 'a' 'b' 'c' 'd' 'e' 'f'; do
-	printf 'Gathering data for answer 2%s...\n' "$i"
-	nc -l -p "$1" | tee "a2$i.txt" | sha256sum > "a2$i.sha256"
+_port="${1:-46400}"
+
+printf 'Starting netcat listener...\n'
+
+_i=0
+while true; do
+	((_i++))
+	_cmd="$(nc -l -p "$_port")"
+	printf ' -> Capturing %s' "$_cmd"
+	_cmd="${_cmd%% *}"
+	_cmd="${_cmd##*/}"
+	nc -l -p "$_port" > "$_cmd$_i.data"
+	sha256sum "$_cmd$_i.data"  > "$_cmd$_i.sha256"
+	printf ' ...%s%s\n' "$_cmd" "$_i"
 done
-
-printf 'sudo dd if=/dev/sda bs=512M count=1' > a3.mbr.cmd
-nc -l -p "$1" | bzip2 -d | dd bs=16M of=a3.mbr.data
-sha256sum a3.mbr.data > a3.mbr.sha256
